Update and rename zimbra to firewall

diff --git a/firewall b/firewall
--- a/firewall
+++ b/firewall
@@ -103,3 +103,75 @@ firewall-cmd --reload
 
 
 
+Shell script to apply DROP
+Here is a shell script, you need to run on Linux based firewall / router / dedicated Linux web / mail server:
+
+#!/bin/bash
+FILE="/tmp/drop.lasso"
+URL="http://www.spamhaus.org/drop/drop.lasso"
+echo ""
+echo -n "Applying DROP list to existing firewall..."
+[ -f $FILE ] && /bin/rm -f $FILE || :
+cd /tmp
+wget $URL
+blocks=$(cat $FILE  | egrep -v '^;' | awk '{ print $1}')
+iptables -N droplist
+for ipblock in $blocks
+do
+ iptables -A droplist -s $ipblock -j LOG --log-prefix "DROP List Block"
+ iptables -A droplist -s $ipblock -j DROP
+done
+iptables -I INPUT -j droplist
+iptables -I OUTPUT -j droplist
+iptables -I FORWARD -j droplist
+echo "...Done"
+/bin/rm -f $FILE
+
+
+
+#!/bin/bash
+
+#Script to add firewall rules to a linux system to completely block
+#all traffic to and from networks in the spamhaus drop list.
+
+#Copyright 2009, William Stearns, wstearns@pobox.com
+#Released under the GPL.  This and other tools can be found at
+#http://www.stearns.org/
+
+#Sole (optional) command line parameter is the file location of the
+#drop list, such as:
+
+#cd /var/lib/
+#wget http://www.spamhaus.org/drop/drop.lasso
+# ./spamhaus-drop /var/lib/drop.lasso
+
+#While the DROP file should be regularly updated, this should 
+#probably be about once per day or less frequently; do _not_ 
+#download DROP more than once an hour.
+
+if [ -n "$1" ]; then
+	DropList="$1"
+else
+	DropList="./drop.lasso"
+fi
+if [ ! -s "$DropList" ]; then
+	echo "Unable to find drop list file $DropList .  Perhaps do:" >&2
+	echo "wget http://www.spamhaus.org/drop/drop.lasso -O $DropList"
+	echo "exiting." >&2
+	exit 1
+fi
+
+if [ ! -x /sbin/iptables ]; then
+	echo "Missing iptables command line tool, exiting." >&2
+	exit 1
+fi
+
+cat "$DropList" \
+ | sed -e 's/;.*//' \
+ | grep -v '^ *$' \
+ | while read OneNetBlock ; do
+	/sbin/iptables -I INPUT -s "$OneNetBlock" -j DROP
+	/sbin/iptables -I OUTPUT -d "$OneNetBlock" -j DROP
+	/sbin/iptables -I FORWARD -s "$OneNetBlock" -j DROP
+	/sbin/iptables -I FORWARD -d "$OneNetBlock" -j DROP
+done
